version: '3'

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    networks:
      - web
    labels:
      - "traefik.backend=wordpress"
      - "traefik.frontend.rule=Host:wordpress.qinjiapeng.cn"
      - "traefik.port=80"
      - "traefik.network=traefik_webgateway"
      - "traefik.frontend.entryPoints=http,https"

networks:
  web:
    external:
      name: traefik_webgateway
