version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    env_file: .env
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - 3306:3306
    networks:
      web:
        aliases:
          - mysql
          - mysql_sha2
          - mysql_native
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_phpmyadmin
    restart: always
    env_file: .env
    networks:
      - web
    labels:
      - "traefik.backend=phpmyadmin"
      - "traefik.frontend.rule=Host:mysql.qinjiapeng.cn"
      - "traefik.port=80"
      - "traefik.network=traefik_webgateway"
      - "traefik.frontend.entryPoints=http,https"

networks:
  web:
    external:
      name: traefik_webgateway
