version: '3'

services:
  ghost:
    image: ghost
    container_name: ghost
    restart: always
    env_file: .env
    volumes:
      - ./volumes/ghost/content:/var/lib/ghost/content
    networks:
      - web
    labels:
      - "traefik.backend=ghost"
      - "traefik.frontend.rule=Host:ghost.qinjiapeng.cn"
      - "traefik.port=2368"
      - "traefik.network=traefik_webgateway"
      - "traefik.frontend.entryPoints=http,https"

networks:
  web:
    external:
      name: traefik_webgateway
