version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qjp.88995
    volumes:
      - ./volumes/data/db:/data/db
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=qjp88995
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=qjp.88995
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    labels:
      - "traefik.backend=mongo-express"
      - "traefik.frontend.rule=Host:mongo.qinjiapeng.cn"
      - "traefik.port=8081"
      - "traefik.network=traefik_webgateway"
      - "traefik.frontend.entryPoints=http,https"

networks:
  web:
    external:
      name: traefik_webgateway
