version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file: .env
    volumes:
      - ./volumes/data/db:/data/db
    networks:
      - web

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    env_file: .env
    networks:
      - web
    labels:
      - "traefik.backend=mongo-express"
      - "traefik.frontend.rule=Host:mongo.qinjiapeng.cn"
      - "traefik.port=8081"
      - "traefik.network=traefik_webgateway"
      - "traefik.frontend.entryPoints=http,https"

networks:
  web:
    external:
      name: traefik_webgateway
